# -*- coding: utf-8 -*-
"""dropna

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0K6Fti-itF0hlyY1uipeIhHzWuzuF0q
"""

import pandas as pd

df=pd.read_csv("/content/Mental Health Dataset.csv.zip")
df.head()

df.tail()

df.isnull().sum()

df.dropna(subset=['self_employed'], inplace=True)

df.isnull().sum()