# -*- coding: utf-8 -*-
"""fillna

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aV64HwQCKLW698c9Ssth_mXlnIZuQJD
"""

import pandas as pd

df=pd.read_csv("/content/Mental Health Dataset.csv.zip")
df.head()

df.tail()

df.isnull().sum()

df['self_employed'].fillna('Unknown', inplace=True)

df.isnull().sum()